name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Check package
      run: twine check dist/*
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    environment: 
      name: pypi
      url: https://pypi.org/p/pcf-config
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    
    - name: Install twine
      run: pip install twine
    
    - name: Check secrets configuration
      run: |
        echo "Checking secrets configuration..."
        if [ -n "${{ secrets.TESTPYPI }}" ]; then
          echo "✅ TESTPYPI secret is configured (length: ${#TESTPYPI})"
        else
          echo "❌ TESTPYPI secret is NOT configured"
        fi
        if [ -n "${{ secrets.PYPI }}" ]; then
          echo "✅ PYPI secret is configured (length: ${#PYPI})"
        else
          echo "❌ PYPI secret is NOT configured"
        fi
    
    - name: Publish to TestPyPI
      run: |
        echo "Publishing to TestPyPI..."
        twine upload --repository testpypi --username __token__ --password ${{ secrets.TESTPYPI }} dist/*
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    - name: Publish to PyPI
      run: |
        echo "Publishing to PyPI..."
        twine upload --username __token__ --password ${{ secrets.PYPI }} dist/*
      if: github.event_name == 'release'
